### PR TITLE
Integration

### PR DESCRIPTION
**Pull request by EnderProyects**
- Add tools to recipe
- Upgradeable armou
- Nerf recipes
- New terrasteel direct block recipe
- Add recipe names

### CODE REVIEW

**Comment by EnderProyects** [comment]
80% of the mod recipes reworked the only left are the infusion ones that I dont know how to handle them

**Comment by boubou19** [comment]
if you add tools to recipes then you must also add recipes in GT assembler because of people who want to automate their recipes in AE2, as tool recipes are slowing down computation of the recipe crafting because AE2 needs to check if tools can be reused after each craft.

Also saying you nerf recipes without explaining why it's needed nor how hard you nerf them makes the nerf questionable, as only 2-3 people willl likely be able to grasp the nerf, closing it from debate.

**Comment by EnderProyects** [comment]
> if you add tools to recipes then you must also add recipes in GT assembler because of people who want to automate their recipes in AE2, as tool recipes are slowing down computation of the recipe crafting because AE2 needs to check if tools can be reused after each craft.
> 
> Also saying you nerf recipes without explaining why it's needed nor how hard you nerf them makes the nerf questionable, as only 2-3 people willl likely be able to grasp the nerf, closing it from debate.

By the nerf I mean that I have make that you can get the advanced blocks to redcuce lag early at the game, (instead of Luv I send them to Hv, but I balance them by adding more materials to the recipe) P,s the changes are in the Advanced botany sugestion and somewhere at magic dev chat

**Comment by EnderProyects** [comment]
> if you add tools to recipes then you must also add recipes in GT assembler because of people who want to automate their recipes in AE2, as tool recipes are slowing down computation of the recipe crafting because AE2 needs to check if tools can be reused after each craft.
> 
> Also saying you nerf recipes without explaining why it's needed nor how hard you nerf them makes the nerf questionable, as only 2-3 people willl likely be able to grasp the nerf, closing it from debate.

Also another thing, for now I have removed the tools that I added yesterday for some recipes because it caused all the errors in other mods, ( maybe because I integrated them wrong in the recipes)

**Comment by EnderProyects** [comment]
Advanced botany recipes that need to be tweaked:
- Add plates and variants of Advanced Botany (AB) Mithirll to greg-tech (Colen)
- Forge of Nidavellir:  Infusion recipe, void metal anvil in the middle, 4 agglo plates, 4 blooks of manasteel, 4 item circuit tier2, 2 runes of air, 2 runes of earth ( and essece)
- Mana Charger: Infusion recipe, mana pylon at the midle, 2 manatide bellows, 4 livingrock slabs, 4 runes of mana, 2 runes of air, 4 mana tablets, 4 mana diamonds
- Terrahoe: Infusion recipe, hoe of growth at the midle, 4 livinwood Twigg, 4 terrasteel plates, 2 earth crystal cluster, 2 runes of eath, 1 flawless olvine and 1 sapphire, 2 floral fertilizer ( replace this item with the how of growth to Bound Sickle BM recipe)
- Nebula armour set: change all the terrasteel armour ingredients with elementium ones ✅ 
- Material destroyer: infusion recipe, Natural core at the middle, 1 Terra Shaterer SS, 1 terra truncator, 1 terra hoe, 1 terra blade, 4 AB Mithrill blocks, 4 glimmering livinwood, 2 flawless mana diamond, 2 flawless ambers
- Mana flower: add 2 primordial pearls, add 4 AB Mithrill nuggets ✅ 
- Blade of space: infusion recipe, Blade of the sea at the midle, 4 AB Mithrill plates, 2 nebula fragments, 2 rod of nebula, 1 rod of bifrost, 1 magic hand mirror,  2 glimmering livingwood, 2 glimering dreamwood, 1 flawless amethyst, 1 flawless Unknow crystal
- Blade of the sea: infusion recipe, Starcaller at the middle. 2 AB Mithrill plates, 4 pieces of nebula, 2 runes of water, 2 runes of air, 1 glimmering dreamwood, 1 rod of seas
- Mithrill ingot: massive nerf, use a block of terrasteelk instead of a nugget, and a gaia spirir ingot instead of a gaia spirit ✅ 
- Nebula fragment: massive nerf, use a block of Mithrill instead of a nugget, rod of the bifrost instead of pixie dust ✅ 
- Rod of nebula: change 1 dreamwood twigg with a staff of travelling

**Comment by boubou19** [comment]
> P,s the changes are in the Advanced botany sugestion and somewhere at magic dev chat

it is not realistic to expect everyone of the team to remember where each discussion/agreement was posted. Discord search is a pain. Also it is even less likely that simple concerned NH players will know where to look.

If you make a PR, you must state clearly what you adress, by giving a link to the github ticket (or discord discussion if it's something trivial), or by simply explaining what you do. In addition of that, PRs adressing an issue must be done after we reached a consensus, otherwise, it's wasted time for the contributor.

**Comment by Dream-Master** [comment]
@EnderProyects i convert this draft until it is done.

**Comment by combusterf** [comment]
Plenty of talking points, and I don't think this merge was not meant to happen :eyes: @Dream-Master @boubou19

**Comment by combusterf** [comment]
Nevermind, this was included 1:1 with a bunch of other commits with the other PR. Still a very sneaky way to lose earlier objections :eyes:

**Comment by Dream-Master** [comment]
> Nevermind, this was included 1:1 with a bunch of other commits with the other PR. Still a very sneaky way to lose earlier objections 👀

yes i was wondering myself why both prs are merged .

**Comment by EnderProyects** [comment]
I should have deleted this merge ( the other is the correct one, this no)

**Pull request merged**
