### PR TITLE
New recipes and fix

### PR DESCRIPTION
**Pull request by EnderProyects**
- Added 3 new blocks: ( WIP, no finished texture) ( Deleted)
   Fountain of Mana: makes recipes like a mana pool but can use pipes ( Deleted)
   Fountain of Alchemy: makes recipes of the catalyst of alchemy but with pipes ( Deleted)
   Fountain of Conjuration: makes recipes of the catalyst of conjuration but with pipes ( Deleted)

- Added some recipes for chanced items so you can get them without chance, tier down some items that used gaia, now they dont, added some qol recipes, like a recipe for the ender air.

### CODE REVIEW

**Comment by EnderProyects** [comment]
@combusterf Now you can check the new blocks I was working in, its missing textures so now they are using the same as the forge of nidavellir, also you can check the new recipes for some items that where tiered way up there, also I have made 3 alternative recipes for some of the chance recipes that used the Ancient Alphirine

**Review by Alastors — CHANGES_REQUESTED** [review]
Honestly my only main thought is that the fountains should all be one block that utilizes the catalysts, I know we've talked about this 1:1 but I think this should be brought up before this pr gets merged

**Comment by Alastors** [comment]
These are new models, could you please provide a picture for this PR so we can see what they look like?

**Comment by EnderProyects** [comment]
> These are new models, could you please provide a picture for this PR so we can see what they look like?

Since I don't have a texture for them, I can't post any model, right now they use the same as the forge, so I don't have to work with the ugly no texture block

**Comment by EnderProyects** [comment]
> Honestly my only main thought is that the fountains should all be one block that utilizes the catalysts, I know we've talked about this 1:1 but I think this should be brought up before this pr gets merged

I think that is better to have 3 independent blocks, that doesn't depends on the catalyst they have bellow, since that is one of the approach I'm trying to make here, the other is that is easier to code it. Although I'm open to suggestions about recipe changes.

**Review by Alastors — CHANGES_REQUESTED** [review]
Absolutely non-negotiable that they need a model and texture before they can be accepted into the pack

**Comment by Dream-Master** [comment]
@Alastors @EnderProyects i set this to draft until a texture is added.

**Review by Alastors — CHANGES_REQUESTED** [review]
No. Ender, we _**don't**_ do **temp** textures...

Please find someone to make a model and submit an actually finished pr...

**Comment by EnderProyects** [comment]
@Alastors As I have said in the description the temp textures are for me to work with, or for anybody that I can find, and since this is a draft there is no problem

**Review by BlueWeabo — COMMENTED** [review]
You can easily still have 3 recipe maps for the Mana Fountain, but please, you don't need 3 different items. You can easilly just implement the code from the [mana pool](https://github.com/GTNewHorizons/Botania/blob/1039b5285435b06e5905f700693e88e37e5759b2/src/main/java/vazkii/botania/common/block/tile/mana/TilePool.java#L209-L210) in botania to use the catalysts instead of 3 blocks. Have only 1! Less models to make too.

Also any reason you couldn't just use the recipes from the Botania mod itself? Can't just use BotaniaAPI.manaInfusionRecipes or BotaniaAPImanaAlchemyRecipes. literally all 3 already exists. and by the looks you are going to be copying them here... You can just register the this block itself for the nei handler for the botania recipe map.

IF you are not going to use the Compats.java file. no need to leave it empty here.

**Comment by EnderProyects** [comment]
About the compat file I uised for testing but in the last pr it was deleted

**Comment by BlueWeabo** [comment]
Any chance to take a look at what else i wrote?

**Comment by EnderProyects** [comment]
> You can easily still have 3 recipe maps for the Mana Fountain, but please, you don't need 3 different items. You can easilly just implement the code from the [mana pool](https://github.com/GTNewHorizons/Botania/blob/1039b5285435b06e5905f700693e88e37e5759b2/src/main/java/vazkii/botania/common/block/tile/mana/TilePool.java#L209-L210) in botania to use the catalysts instead of 3 blocks. Have only 1! Less models to make too.
> 
> Also any reason you couldn't just use the recipes from the Botania mod itself? Can't just use BotaniaAPI.manaInfusionRecipes or BotaniaAPImanaAlchemyRecipes. literally all 3 already exists. and by the looks you are going to be copying them here... You can just register the this block itself for the nei handler for the botania recipe map.
> 
> IF you are not going to use the Compats.java file. no need to leave it empty here.

1 Since is an advanced version I dont know why it has to still be using the catalyst bellow the block, instead this ones has it in the block itself, so once you set it up you dont need to change it, allso that is designed so the items are inserted at the top and extracted from bellow, in order that can be used with more imagination without having pipes from the sides. Also for the model I only need 1 the other two can be colored variants, yellow for the Alchemy catalyst and green for the Conjuration catalyst.

2 Also that since I´m not a very good programmer I dont know how to detect if x block is near or bellow to change the recipes, and that with the original code of AB using  the botania API means a whole recoding of more of half the mod, ( and I dont have many free time to learn how to make some things)

**Comment by EnderProyects** [comment]
P.s sorry for my bad English and my dislexia

**Comment by BlueWeabo** [comment]
Just because the old code by the original author of Advanced Botany is doing things like this, doesn't mean one should continue the trend. IF the trend was continued in GT5u instead of doing the large scale refactors many things would be lost.

I think you should, even if it takes more time, try to learn the ropes, explore what another mod gives to you, see if you can improve things around the mod, ect. I don't think you should be continuing a trend that will only slow down development later down the line.

**Comment by BlueWeabo** [comment]
But this is just my opinion. You can do what you want.

**Comment by EnderProyects** [comment]
> But this is just my opinion. You can do what you want.

It doesn't look like I could do that

**Comment by EnderProyects** [comment]
@Alastors now you can accept this pr since now only fix some tier recipes and add the GT Mithril plates to the ones that used the iongot, as well as conversion recipes and alternative recipes for the chance ones?

**Comment by Alastors** [comment]
> @Alastors now you can accept this pr since now only fix some tier recipes and add the GT Mithril plates to the ones that used the iongot, as well as conversion recipes and alternative recipes for the chance ones?

Nah, with how this entire situation has gone, this is going to need to have higher approval from like @boubou19

**Comment by EnderProyects** [comment]
@boubou19 Why this pr whas closed?

**Comment by boubou19** [comment]
AB is removed from the pack. And Alastor is making a mod to add the valuable stuff of AB without having to deal with this giant pile of mess that is AB's code.

**Comment by Dream-Master** [comment]
@boubou19 for tesing i re add AB in the pack. Sure there is no final vote about to add the mod but let this pr open until we make this vote

**Comment by Alastors** [comment]
> @boubou19 for tesing i re add AB in the pack. Sure there is no final vote about to add the mod but let this pr open until we make this vote

Could we not though? Couldn't you just instead do a final vote instead of bringing it into the pack and _then_ doing a final vote?

**Comment by Dream-Master** [comment]
@boubou19 @combusterf @Alastors @EnderProyects 
i wasnt aware a new mod was planed. If we not continue AB mod and not add it sure we can close this pr. But speak with me about it so i can remove the repo from github , jenkins and maven or make it deprecated

**Pull request closed without merging**
