### PR TITLE
Updated buildscript

### PR DESCRIPTION
**Pull request by EnderProyects**

### CODE REVIEW

**Comment by Dream-Master** [comment]
Yea that looks better. The package yml is not needed

**Comment by EnderProyects** [comment]
So I just delete it and Pr again?

**Comment by BlueWeabo** [comment]
no, just delete the file and commit it as deleted

**Comment by EnderProyects** [comment]
Can this one be reviewed and merged since the mod is not included right now in the pack but it doesnt get forgotten? >w<

**Comment by Dream-Master** [comment]
sure after stable ill take care

**Comment by EnderProyects** [comment]
Dream... UwU, can you merge it so I can start working in the recipes? ( gregging some andd botania integration) :3

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
